<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>SH.Framework.Library.Cqrs</PackageId>
        <Version>3.0.1</Version>
        <Authors>Muharrem Kaçkın</Authors>
        <Company>Strawhats Company</Company>
        <Description>A lightweight and high-performance library implementing the Command Query Responsibility Segregation (CQRS) pattern for .NET 10.0. Provides clean architecture and separated responsibilities in modern .NET applications with support for Request/Response, Notifications, and Pipeline Behaviors. Features comprehensive interfaces for dependency injection integration and projector-based query operations.</Description>
        <PackageProjectUrl>https://github.com/muharremkackin/sh-framework-cqrs</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageTags>asp.net;cqrs</PackageTags>
        <RepositoryUrl>https://github.com/muharremkackin/sh-framework-cqrs</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <DebugType>portable</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <Copyright>Copyright © Strawhats Company 2024</Copyright>
        <Product>SH Framework CQRS Library</Product>
        <TargetFrameworks>net9.0;net10.0;net8.0</TargetFrameworks>
        <LangVersion>12</LangVersion>
        
    </PropertyGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.201">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.14" />
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    
    <ItemGroup>
      
    </ItemGroup>

    <ItemGroup>
        <None Include="./../LICENSE" Pack="true" PackagePath="" />
        <None Include="./../README.md" Pack="true" PackagePath="" />
    </ItemGroup>

</Project>
